### ISSUE TITLE
Startup time

### ISSUE THREAD

**Issue by hugokrantz** [ibito/linkify#1]
"This package added 547ms to startup time."

Not really a big issue, but this package is by far the 'slowest' package I have, and still it's som non-complex. Maybe something could be done?

**Comment by ibito** [comment]
Just updated the package, I moved the gif to imgur, so it won't load on atom (looks like that's what it was doing).

**Comment by ibito** [comment]
![Screenshot](http://i.imgur.com/htH2WIo.png)

**Comment by hugokrantz** [comment]
Nice!
